/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TicketsRouteImport } from './routes/tickets'
import { Route as ApiFoldersRouteImport } from './routes/api/folders'
import { Route as ApiMeRouteImport } from './routes/api/me'
import { Route as ApiTicketsRouteImport } from './routes/api/tickets'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiTicketsIdRouteImport } from './routes/api/tickets/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketsRoute = TicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFoldersRoute = ApiFoldersRouteImport.update({
  id: '/api/folders',
  path: '/api/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeRoute = ApiMeRouteImport.update({
  id: '/api/me',
  path: '/api/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTicketsRoute = ApiTicketsRouteImport.update({
  id: '/api/tickets',
  path: '/api/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTicketsIdRoute = ApiTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTicketsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/tickets': typeof TicketsRoute
  '/api/folders': typeof ApiFoldersRoute
  '/api/me': typeof ApiMeRoute
  '/api/tickets': typeof ApiTicketsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tickets/$id': typeof ApiTicketsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/tickets': typeof TicketsRoute
  '/api/folders': typeof ApiFoldersRoute
  '/api/me': typeof ApiMeRoute
  '/api/tickets': typeof ApiTicketsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tickets/$id': typeof ApiTicketsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/tickets': typeof TicketsRoute
  '/api/folders': typeof ApiFoldersRoute
  '/api/me': typeof ApiMeRoute
  '/api/tickets': typeof ApiTicketsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/tickets/$id': typeof ApiTicketsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/tickets'
    | '/api/folders'
    | '/api/me'
    | '/api/tickets'
    | '/api/auth/$'
    | '/api/tickets/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/tickets'
    | '/api/folders'
    | '/api/me'
    | '/api/tickets'
    | '/api/auth/$'
    | '/api/tickets/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/login'
    | '/tickets'
    | '/api/folders'
    | '/api/me'
    | '/api/tickets'
    | '/api/auth/$'
    | '/api/tickets/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  TicketsRoute: typeof TicketsRoute
  ApiFoldersRoute: typeof ApiFoldersRoute
  ApiMeRoute: typeof ApiMeRoute
  ApiTicketsRoute: typeof ApiTicketsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tickets': {
      id: '/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof TicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/folders': {
      id: '/api/folders'
      path: '/api/folders'
      fullPath: '/api/folders'
      preLoaderRoute: typeof ApiFoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/me': {
      id: '/api/me'
      path: '/api/me'
      fullPath: '/api/me'
      preLoaderRoute: typeof ApiMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tickets': {
      id: '/api/tickets'
      path: '/api/tickets'
      fullPath: '/api/tickets'
      preLoaderRoute: typeof ApiTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tickets/$id': {
      id: '/api/tickets/$id'
      path: '/$id'
      fullPath: '/api/tickets/$id'
      preLoaderRoute: typeof ApiTicketsIdRouteImport
      parentRoute: typeof ApiTicketsRoute
    }
  }
}

interface ApiTicketsRouteChildren {
  ApiTicketsIdRoute: typeof ApiTicketsIdRoute
}

const ApiTicketsRouteChildren: ApiTicketsRouteChildren = {
  ApiTicketsIdRoute: ApiTicketsIdRoute,
}

const ApiTicketsRouteWithChildren = ApiTicketsRoute._addFileChildren(
  ApiTicketsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  TicketsRoute: TicketsRoute,
  ApiFoldersRoute: ApiFoldersRoute,
  ApiMeRoute: ApiMeRoute,
  ApiTicketsRoute: ApiTicketsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
